### ISSUE TITLE
Show login vs register for returning users

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#250]
Detect whether a user has logged in or registered before to determine which scene to show (login or register)

**Comment by jwest60** [comment]
pr submitted #534

**Comment by almasaeed2010** [comment]
merged! Thanks @jwest60 

Here is the new look btw

![img_497e8d8b4372-1](https://user-images.githubusercontent.com/1512664/47043744-69fa2e00-d15c-11e8-98e2-c05614a64f76.jpeg)
