### ISSUE TITLE
Google Analytics integration

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#252]
`react-native-google-analytics-bridge`

**Comment by almasaeed2010** [comment]
We are now using `react-native-firebase` to implement this

**Comment by almasaeed2010** [comment]
Events to record:

- [ ] Visiting a screen
- [ ] Registration through the app
- [ ] Device info
- [ ] Errors
- [ ] Observations recorded vs uploaded/synced
- [ ] Time spent filling the form (categorize by tree type)
