### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#253]
We'd like to send push notifications to users when they haven't used the app in a while to remind them to participate!

**Comment by almasaeed2010** [comment]
- [ ] unpublished entries.
- [ ] notification alerts for “tree of interest”. IE Ash in Ohio or something
- [ ] Reminder to use the app if it hasn’t been accessed for over a month?

**Comment by almasaeed2010** [comment]
This seems to be the most popular module to do this:
https://github.com/zo0r/react-native-push-notification

**Comment by bradfordcondon** [comment]
@almasaeed2010 i believe this is fully implemented yes?  can i close?

**Comment by almasaeed2010** [comment]
2 out of 3 are implemented

**Comment by almasaeed2010** [comment]
I moved this item down here to discuss it:
- [ ] notification alerts for “tree of interest”. IE Ash in Ohio or something


----

To implement this we need to ask the user to grant us access to their location even when they are not using the app. We'll also need to figure out background jobs to get this to work along with bundling a list of each tree and the locations of interest. I don't feel like this worth that much work but if really wanted we can figure out. 

Thoughts on whether we should or shouldn't go for it?
