### ISSUE TITLE
Tree list for 'other' improvements

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#255]
* Sort alphabetically
* Include more Trees (broader range, include invasives?)

**Comment by almasaeed2010** [comment]
Our next release might end up having many trees 3000+. I suggest creating a script that generate json files for those trees that can be seeded into realm. Using, realm here will make it easier and faster to filter through observations. The only issue is how do we ship a pre-seeded realm database. Or will have to seed on app install?

**Comment by almasaeed2010** [comment]
It's possible to bundle a realm DB with the app (see https://www.realm.io/docs/swift/latest/#bundling-a-realm).
