### ISSUE TITLE
[Android?]  Submitting observation gets network error but submits, resulting in dupes

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#305]
See for example https://treesnap.org/observation/605

>That said, I *thought* this one had uploaded back in Nov but opened the app yesterday for the first time since then and had a notice that I had observations to upload.  Every time I used the upload button I got a network error.  From the website looks like I had 6 of the same sample upload so several of my attempts must have processed eventually.

>For the observation you’ve uploaded, to confirm - after you push submit, you get a network error message.  However, on the site, the observation is uploaded?

**Comment by almasaeed2010** [comment]
We need to ask them whether the Network error message appeared immedietly or after more than 7 seconds

**Comment by almasaeed2010** [comment]
@bradfordcondon do we have their email?

**Comment by almasaeed2010** [comment]
Hopefully fixed in 1.2. From now on the app will request to delete the observation if a failure occurs before the completion of the upload.

**Comment by almasaeed2010** [comment]
And regarding the error, the user should get better error messages too that will help us pin point the issue if it occurs again
