### ISSUE TITLE
[iphone] app freezes on camera zoom

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#307]
When taking photos, if you zoom, the app freezes (no buttons work). Only way to exit is to press home button and exit app.
Iphone 8, app version 1.1.3

**Comment by bradfordcondon** [comment]
Recreated bug on iphone 7. should test on Android too.

**Comment by almasaeed2010** [comment]
Done in upgrades therefore will be published in 1.2 release
