### ISSUE TITLE
Twitter integration?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#328]
This is from Ellen's wishlist.  How hard would it be to add a twitter integration component, where after a tree is submitted the modal includes a link to "share this tree on twitter" and tapping it opens the user's twitter client with a link to the tree on the server?

**Comment by almasaeed2010** [comment]
Not hard but we'll need to use ReactNative's WebView https://facebook.github.io/react-native/docs/webview.html

**Comment by bradfordcondon** [comment]
i was thinking something like https://github.com/tipsi/tipsi-twitter

I was hoping it would just launch the twitter app...

**Comment by almasaeed2010** [comment]
This seems like an authentication library with Twitter (login using twitter) rather than a sharing library

**Comment by bradfordcondon** [comment]
you're right thanks.  I was thinking the easiest way and best UX is the "send to twitter app" approach but a webview might be better?  

Obviously it ahs to be fairly easy if we're going to implement it at this stage in the game.

**Comment by almasaeed2010** [comment]
Webview should be pretty easy but if we can use iOS and Android internal links, I'd prefer that approach too. My only question is how do we determine if the app is installed and would we need to implement a fallback solution if it isn't?

**Comment by bradfordcondon** [comment]
if the component exists, there would be a "twitter is installed" flag or something.  and if it is, the submission message includes the twitter option, if not, theres no link and it never shows up.

**Comment by almasaeed2010** [comment]
Added a share button. Available in 1.2.0
