### ISSUE TITLE
ID photos cut off on side of screen

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#341]
Full screen photos on id tab for hemlock, ash and elm are cut off on the left and right side.

I've only noticed this on the most recent update (1.2.0 on my phone).

![img_2498](https://user-images.githubusercontent.com/508122/38456799-94d44860-3a56-11e8-97fc-226b814215ee.PNG)
![img_2499](https://user-images.githubusercontent.com/508122/38456800-94ea1f1e-3a56-11e8-9b6c-1f0f30fd473b.PNG)

**Comment by mestato** [comment]
Also a problem for pictures associated with specific questions (tree diameter) and for distribution maps.

**Comment by almasaeed2010** [comment]
fixed.

- [ ] Test on Android device
