### ISSUE TITLE
New Collection missing from Dropdown selection on Observation page

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#342]
To reproduce:
Start on the observation page. Click star, and create a new collection. Go to another observation and click star again. The new collection does not appear in the "Collection Name" dropdown box. 

Paging forward or back doesn't repopulate the drop down, but reloading the whole page does.

Only tested as an admin.

**Comment by bradfordcondon** [comment]
sounds a lot like https://github.com/statonlab/Treesnap-website/issues/211

**Comment by mestato** [comment]
You are correct, didn't see that one.

**Comment by bradfordcondon** [comment]
But that ones closed

**Comment by almasaeed2010** [comment]
Fixed live. The previous one wasn't an issue with the admin view. Now fixed on both admin and non-admin.
