### ISSUE TITLE
Torreya tasks

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#346]
- [x] Vet material
- [x] Format images

- [x] Add new tree

- [x] Add new questions as necessary

- [x] Configure geolocation

Seperate issue for website...

**Comment by bradfordcondon** [comment]
Recycled questions:
diameter, height, seedsBinary


could have been recyceld but werent:
* cones  (ours was true/false.  They want male, female)

new questions added:

```
  //Torreya questions
  numberRootSprouts: {
    label : 'Root Sprouts',
    description: 'How many root sprouts are present?',
    numeric: true,
    units: 'sprouts',
  },
  deerRub: {
    label: "Deer Rub",
    description : 'Is there evidence of deer rub on the trunk?',
    selectChoices: ['Present', 'Absent', 'Not sure'],
    placeHolder : 'Please select'
  },
  torreyaFungalBlight: {
    label : "Fungal Blight",
    description: 'Do you see disease symptoms? Needles could be lighter in color, yellow, or absent. Cankers can be on trunk or branches.',
    selectChoices: ['Present', 'Absent', 'Not sure']

  },
  conesMaleFemale : {
    label : 'Cones',
    description: 'Are cones present?',
    selectChoices: ['Absent', 'Male present', 'Female present', 'Not sure']
  }


```

**Comment by bradfordcondon** [comment]
* need to set up the geolocation thing.
* Some questions lack images.

**Comment by almasaeed2010** [comment]
For location, this is what we'll need

```
locations: {
  only: ['Florida']
}
```

**Comment by almasaeed2010** [comment]
That will automatically consider florida and any neighboring states but only the edge parts of a neighboring state.

**Comment by bradfordcondon** [comment]
oh seriously it auto includes the edges of neighbors? thats awesome.

**Comment by almasaeed2010** [comment]
yep :)

**Comment by almasaeed2010** [comment]
Need to remember how to add a placeholder here:
![screen shot 2018-04-30 at 12 52 51 pm](https://user-images.githubusercontent.com/1512664/39439413-76d23544-4c75-11e8-925f-b6f4c279b144.png)

**Comment by bradfordcondon** [comment]
oops, yeah thats easy, just need `    placeHolder  :  sprouts` in `config.js`

**Comment by bradfordcondon** [comment]
Some questions, comments, and suggestions:

comments:
* If you notice that a couple of photos are oversized and clipped off (the map for example), that’s a bug with our image library, we are aware and working on it, hopefully will be fixed by next release.
* I’ve cropped and resized some photos as necessary.  Portrait style photos look best on mobile as that matches the phone shape (see below re: the landscape style photos).
* Other requested info is going on the TreeSnap website for example the organizational logo.

Questions:
* I picked the “icon” photo for Torreya from your pool. If you’d prefer a different photo please let me know.
* Maps: I only included 2 for simplicity.  I want to keep the USGS map for consistency with other trees, maybe I can add a big red arrow pointing to to the region, what do you think?
* I included all photos in the general info modal.  If some photos you only want in the relevant question (IE disease photos let me know).
* which photos belong in the more info for cones question?  I only see a male cones photo, and the Black and white field guide page.  I think I was able to place the others correctly but if i’ve made a mistake let me know.


Suggestions:
* Do you have photos for Deer rub, or a brief description of what to look for?
* Root sprouts: Can we make this question optional IE someone can submit without clicking on it?  I think it’s awkward to have to type in 0.
* Root sprouts: maybe a sentence or two on what these are/what to look for?  Not obvious to a non-tree person such as myself.
* As you probably notice, landscape format photos don’t look good on mobile without reorienting them.  I would consider replacing, or removing, those photos.


Thank you again for putting together an excellent submission.

**Comment by bradfordcondon** [comment]
# round 2 edits
- [ ] Seed photos?

- [ ] Standardize capitalization

**Comment by bradfordcondon** [comment]
Hi Everyone:

Please find a youtube video walking through the Torreya addition below.

https://youtu.be/IBf1yfjFLjg

Some questions, comments, and suggestions:

comments:
* If you notice that a couple of photos are oversized and clipped off (the map for example), that’s a bug with our image library, we are aware and working on it, hopefully will be fixed by next release.
* I’ve cropped and resized some photos as necessary.  Portrait style photos look best on mobile as that matches the phone shape (see below re: the landscape style photos).
* Other requested info is going on the TreeSnap website for example the organizational logo.  this info is available now: please see https://treesnap.org/partners and https://treesnap.org/trees


Questions:
* I picked the “icon” photo for Torreya from your pool. If you’d prefer a different photo please let me know.
* Maps: I only included 2 for simplicity.  I want to keep the USGS map for consistency with other trees, maybe I can add a big red arrow pointing to to the region, what do you think?
* I included all photos in the general info modal.  If some photos you only want in the relevant question (IE disease photos let me know).
* which photos belong in the more info for cones question?  I only see a male cones photo, and the Black and white field guide page.  I think I was able to place the others correctly but if i’ve made a mistake let me know.
* I realize as im writing this that you would like the 3 seed photos associated with the seed question?  
* Ellen is making an ID video for Torreya and other species this summer, who would be the best person to contact about that?  She envisions formatting all the ID videos similarly (simple and short) but she would love to have a representative of  theirs do a short in-field video component I can include.

Suggestions:
* Do you have photos for Deer rub, or a brief description of what to look for?
* Root sprouts: Can we make this question optional IE someone can submit without clicking on it?  I think it’s awkward to have to type in 0.
* Root sprouts: maybe a sentence or two on what these are/what to look for?  Not obvious to a non-tree person such as myself even looking at the pictures.
* As you probably notice, landscape format photos don’t look good on mobile without reorienting them.  I would consider replacing, or removing, those photos.

* We have the option to associate photos with questions.  For example, if a user says “yes” to cones, you can have a new camera question appear below (optional) for them to take a photo of the cones.  Would this be helpful?  If so, for which questions?


Thank you again for putting together an excellent submission. Please let me know if you have any questions or comments.

Bradford

**Comment by bradfordcondon** [comment]
ignoring seed photos for now: better to use the base modal with no images...  see #357

**Comment by bradfordcondon** [comment]
# Photos issues
## Disease
* Diseased needles photo.  Several different diseases in the photos. We suggest you look at the chestnut questions.  Users can select one, multiple, or none specific disease symptoms they see.  This includes root sprouting. Given this possibility, should we also just include root sprouts as a question on the disease symptoms section instead of its own question?
 
 Rename Fungal blight to Disease Symptoms.


 clarify what symptoms they are looking for.
sounds like:
* Foliar
* Stem Cankers
* Root Sprouts

Cut the diseased tree one: can't see clearly.

Cut last stem canker photo.


(Copy paste chestnut choices)


>Root Sprouts – Not optional. Could you change the question to “Number of living root sprouts” and remove 0 from the options? The general description already has “…most trees in wild native habitat are root sprouts just a few feet tall…” and “Root sprouts die before reaching maturity…”. You could add clarification in the question, 


>“Root sprouts are stems growing up from the ground where a mature Torreya tree once lived, growing from the root of the dead tree. There may be dead stems. Count only the ones showing green needles.” 

### Root sprouts
* Move root sprout description to photo caption.
* Move Q to disease.
* If we need the question, change to "How many living root sprouts are present".

## Cones

What is the difference between female seed and female cone?  THere is only one diagram of female cone: the black and white textbook.  Are they the same?  If not, is there a female cone photo?

## Deer rub

Move "look for smooth stems with bark missing" to the description.

**Comment by bradfordcondon** [comment]
## cones

* Cone photos are forthcoming.

## optional camera

## disease symptoms
* new info from ellen.

## Extra question

* Habitat type questions?   Shade?

## Deer rub 
change to - 
Absent but caged
Absent

# description

add sentence about don't moving the tree, don't want to spread the disease...
