### ISSUE TITLE
Large images

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#347]
Some ID images have a width of 1500px+ 

We should limit that to 600-800px

**Comment by bradfordcondon** [comment]
see also #418

**Comment by almasaeed2010** [comment]
Just a note that this refers to in-app informational images and not images taken by the user.

**Comment by almasaeed2010** [comment]
Ok went through and minimized all images in the app. Most previously uncompressed images lost 70% of their size since they were a lot wider than what we need.

When it comes to automating this, I couldn't find a script that does as good a job as https://compressjpeg.com and https://compresspng.com

I suggest we keep using these website for compressing ID images.
