### ISSUE TITLE
numeric modal does not update placeholder text

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#354]
see image.  ap roblem for the root sprouts as well as the pre-existing tree height, both say "enter diameter".

dont know if the modal doesnt accept a props, or if its getting passed wrong props.

![screen shot 2018-05-02 at 1 00 03 pm](https://user-images.githubusercontent.com/7063154/39537861-d77022a0-4e08-11e8-9340-2435dce3f18d.png)

**Comment by almasaeed2010** [comment]
You seem to have already fixed this?

I added the placeholder to `Root Sprouts` and seems to be working correctly.

**Comment by almasaeed2010** [comment]
Oh nevermind I see the issue is in the modal itself not the form.

**Comment by almasaeed2010** [comment]
Fixed in PR #360

The numeric type modal expects 2 placeholders apparently. `placeHolder` to show in the form list itself and `numberPlaceHolder` to show in the modal's text input. Simply specifying `numberPlaceHolder` in config.js fixes the issue.
