### ISSUE TITLE
conditionally display images

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#357]
Question config looks like
```
 seedsBinary        : {
    label        : 'Seeds',
    selectChoices: [
      'Yes', 'No', 'I\'m not sure'
    ],
    description  : 'Are seeds present?',
    placeHolder  : 'Are seeds present?',
    camera       : ['Yes'],
    conditional : {
      Torreya: {
        images: [],
        captions: []
      }
    }
  },
```

then in the `form.js` the question should check if there is a conditional field for that organism (key should === tree name)  and fetch those values to pass into/overwrite defaults 

conditional should only be for label (2x this doesnt mess up validation or sending to server), images, captions, description, placeholder.  NOT for choices, because we dont want to mess up the custom filters on the website.

**Comment by almasaeed2010** [comment]
I am reopening because currently this only applies to images and captions so I'll reimplement to completely override anything

**Comment by bradfordcondon** [comment]
i think we dont want to override options and labels without some thought, because those are the keys that get turned into filters right?

**Comment by almasaeed2010** [comment]
Correct. If we do override them, we'll need to specify the changes on the website. The website, however, has its own set of filters per tree so we can easily update those filters if needed and run a migration to add the values as necessary. So same plane, add as an issue if a value changes or gets overriden.

**Comment by almasaeed2010** [comment]
Ok this is done now such that any property can be replaced as required (see #371)

**Comment by bradfordcondon** [comment]
cool thanks!  I'll move ahead with updating the torreya questions tomorrow am then.
