### ISSUE TITLE
express to host live demos of app for partners?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#365]
Instead of sending youtube videos, what if we could host a web demo of their tree?  Isn't that what express is for?  Are there major obstacles preventing us from doing this?

**Comment by mestato** [comment]
I'm not sure what the advantage of express is, but you can host a virtual meeting with live demos via Zoom any time. It is still nice to have videos that we can embed in the website, which means they can be viewed by other people later on and used by partners to share with their own volunteer networks.

**Comment by bradfordcondon** [comment]
The first draft videos im sending out aren't production ready.  It's just touring the images, descriptions, questions.  They'll be deleted when the tree is added.

Express is basically a live version of the app in a web browser.   People can click through the questions and check on their own pace, etc.
That said I just remembered that i think it requires launching an instance etc, its not suitable to keep running.

**Comment by bradfordcondon** [comment]
this is not the purpose of express unfortunately, so closing.
