### ISSUE TITLE
4.4.1 android wont launch

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#400]
app wont launch on evan's phone android 4.4.1.  i remember this being a galaxy model but need to check @mestato  ?

First check in Android Studio emulator.  If that cant reproduce bug, test launching device in a "farm" service such as one [offered through amazon](https://aws.amazon.com/device-farm/?sc_channel=PS&sc_campaign=acquisition_US&sc_publisher=google&sc_medium=device_farm_nb&sc_content=android_general_testing_e&sc_detail=android%20device%20testing&sc_category=device_farm&sc_segment=198763901202&sc_matchtype=e&sc_country=US&s_kwcid=AL!4422!3!198763901202!e!!g!!android%20device%20testing&ef_id=WqBKSgAAAGL5LTa8:20180524152258:s).

This is a good test for such a service as we ramp up user base and anticipating having more of these sorts of problems

**Comment by almasaeed2010** [comment]
Refer to #386

**Comment by bradfordcondon** [comment]
closing as duplicate.
