### ISSUE TITLE
Testing Goals

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#401]
Scaling up for #392 means we need more robust testing.  Let's discuss.

* Abstracting code so we do more vanilla JS unit testing
   - great, where do we start? 
* Testing JSX... Using Jest snapshots is an option for scenes but i dont think we're in love with this.  I think this is our bottom priority.
* CI testing ideally checks that forms submit, db can be retrieved from, and obs can be sent to server.
* [Use AWS device-like farm to make this way more robust?](https://aws.amazon.com/device-farm/?sc_channel=PS&sc_campaign=acquisition_US&sc_publisher=google&sc_medium=device_farm_nb&sc_content=android_general_testing_e&sc_detail=android%20device%20testing&sc_category=device_farm&sc_segment=198763901202&sc_matchtype=e&sc_country=US&s_kwcid=AL!4422!3!198763901202!e!!g!!android%20device%20testing&ef_id=WqBKSgAAAGL5LTa8:20180524152258:s)

**Comment by almasaeed2010** [comment]
This is now implemented using JEST.
