### ISSUE TITLE
submission issue, 1.2.0

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#402]
iOS
app version 1.2.0
ellen's phone has a bunch of observations she took in mexico. trying to sync, it says "sucessfuly uploaded" but no trees get syncedwhen pushing the sync all on observations, or the upload your observations on the landing page.

However, on observations page, i can upload **individual** observations.

**Comment by almasaeed2010** [comment]
Let's test this with 1.3.2 just in case it got fixed already.

**Comment by almasaeed2010** [comment]
See #423
