### ISSUE TITLE
Android crash on build 1063

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#407]
[Firebase crash report, Android](https://console.firebase.google.com/project/treesnap-d64df/monitoring/app/android:com.treesource/cluster/317ea80f?utm_source=alerts&utm_medium=email&utm_campaign=crash&utm_content=cluster&pli=1&duration=2592000000).  Device is moto G (4).

full error below
```
Exception java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:28)
com.RNFetchBlob.RNFetchBlobFS.cp (RNFetchBlobFS.java:484)
com.RNFetchBlob.RNFetchBlob$5.run (RNFetchBlob.java:167)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
```

**Comment by almasaeed2010** [comment]
I don't see this happening anymore. It's likely that it is a specific device issue or a launch error that only happened once and restarting the app just fixed it.

**Comment by bradfordcondon** [comment]
last occurrence was `Jun 14, 2018, 2:20:36 PM`.  I'd agree with that assesment except it happened 2x (to the same user).

**Comment by bradfordcondon** [comment]
I apologize: above comment is wrong.  it has happened 2x, each time to a different user.  therefore let's hope it was a launch only error since we havent seen it coem back.

**Comment by almasaeed2010** [comment]
It's no longer happening on new release.
