### ISSUE TITLE
ProGuard mapping file to improve firebase crash logs?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#408]
>Upload a ProGuard mapping file to deobfuscate future stack traces for version 1063

**Comment by almasaeed2010** [comment]
I am going to install and enable crashlytics since it could save us a lot of time in the future

**Comment by almasaeed2010** [comment]
<img width="1552" alt="screen shot 2018-06-26 at 4 30 45 pm" src="https://user-images.githubusercontent.com/1512664/41937447-4eb8aa0a-795e-11e8-96b3-a03107a2ac77.png">


Crashlytics is now installed.
