### ISSUE TITLE
Add to the List of Other Species

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#419]
When users begin typing the species, the app tries to suggest a species name to save time and to prevent misspellings. While 4000 species might make the suggestions too slow to be helpful, we can add your most common species. We’ll have to test to see about speed but we think adding up to 400 additional species to the suggestion list should still be fast enough to be useful.

**Comment by mestato** [comment]
List of 111 species from Marysol sent over email as xlsx file.

**Comment by almasaeed2010** [comment]
Ellen requested to add:

```
Vitis rotundifolia (common name= muscadine)
```

**Comment by almasaeed2010** [comment]
List that Marysol sent: [Species for Tree Snap.xlsx](https://github.com/statonlab/Treesnap-mobile/files/2155643/Species.for.Tree.Snap.xlsx)

**Comment by mestato** [comment]
We've decided we aren't going to add common names for these species - all FSC contributors should know latin names.

**Comment by almasaeed2010** [comment]
@mestato Currently our system requires at least one name but that's not a big problem. We can easily tweak to accommodate this.
