### ISSUE TITLE
Create FSC Group

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#421]
FSC will need to be able to track users associated with their program. We will help to create a public group that their users can associate with. This will allow the FSC scientists to filter and download tree observations to just those reported by FSC group members.

**Comment by bradfordcondon** [comment]
created as https://treesnap.org/account/group/39

It's autoshare, and its discoverable.

**Comment by bradfordcondon** [comment]
no one has joined this group.  however we did it, so... im closing.
