### ISSUE TITLE
Add hemlock species question

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#437]
Hemlock species:

- Eastern hemlock (Tsuga canadensis)
- Carolina hemlock (Tsuga caroliniana)
- Other hemlock species
- I'm not sure

**Comment by almasaeed2010** [comment]
Do we have example images and samples for this?

So far this is what we have:
<img width="499" alt="screen shot 2018-06-28 at 4 41 41 pm" src="https://user-images.githubusercontent.com/1512664/42059644-288ab180-7af2-11e8-8145-6b751ba7ac85.png">

**Comment by bradfordcondon** [comment]
The images already in the app can be re-linked here: there are a couple that compare eastern and carolina.

These are the only two hemlock species that will occur in Eastern North America.  There are 11 other species, 3 of which are native to the continent.  I don't think we'll provide content for those.

**Comment by almasaeed2010** [comment]
I'll add those there. thanks!
