### ISSUE TITLE
Stand tagging

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#471]
Sometimes you are amid a large stand of trees of the same species, and you don't want to tree snap them all. Ideas:
- modify the trees nearby question
- ignore, suggest to individuals they put that in the comments
- advanced options

**Comment by mestato** [comment]
Emailed Ben to see if TACF wants this. If not not sure who does.

**Comment by mestato** [comment]
This was requested for white oak

**Comment by almasaeed2010** [comment]
Let's create an issue on the website to add the filters and the metdata. Can you take care of that @jwest60?
