### ISSUE TITLE
Topo overlay and show your own location on the map

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#472]
Request from Leigh of Torreya - is there a simple way to add a topo layer to the app map? Request from Leigh of Torreya and Ben of FRI -is there a way to add an indicator of user's location to map app?

**Comment by almasaeed2010** [comment]
So we can add a real topo layer on android devices only. But we'll offer a hybrid/satellite option for iOS

**Comment by almasaeed2010** [comment]
Copying here for reference:

- Adds a "locate me" button to zoom to the current user's location
- Adds a top tab bar to allow the user to choose between map types
- Adds an indicator for the current location of the user
