### ISSUE TITLE
Is white oak observe list of questions too technical?

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#476]
Branch height was noted as a confusing/intimidating question. Is it needed? Number of acorns (few, some, many) really vague.

**Comment by bradfordcondon** [comment]
re: acorns, see #247 . I never thought of a good way to fix it beyond switching the question to "yes/no"

**Comment by mestato** [comment]
Change to: "Approximately high high up is the first main branch of the tree? (Its ok to ignore small branches, i.e. suckers, at the base)."

**Comment by almasaeed2010** [comment]
done. Thanks @jwest60
