### ISSUE TITLE
Inches AND feet

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#483]
request for inches AND feet input boxes in measurement.

I think the answer is no, we don't want this.  I want to check with @ellen first.

**Comment by almasaeed2010** [comment]
I agree with you in that we shouldn't add this since it'll make filtering a lot more complicated (from a dev perspective).

**Comment by almasaeed2010** [comment]
This issue got brought up again. I think we can provide a simple solution that will convert inches to feet upon submission of the form. But I'll put this on the back burner for now.

**Comment by almasaeed2010** [comment]
this is done
