### ISSUE TITLE
Missing photos for some observations on website (not uploaded correctly?)

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#485]
For example: https://treesnap.org/admin/observation/1839

I have a photo on my phone of this tree but it does not appear on the website. My app does not indicate there are any pending uploads. There are quite a few of these image-less observations from a number of users other than me.

https://treesnap.org/admin/observation/1778
https://treesnap.org/admin/observation/1868

**Comment by almasaeed2010** [comment]
Fixed in v1.4.1
