### ISSUE TITLE
Add larch

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#488]
Olivia is the contact person, here is her document:
https://docs.google.com/document/d/17MJsKlambG8B3w_IC9yO2TrkXjGyVxeLIo3znU_1NoU/edit?usp=sharing

This probably another good candidate to use the "Show trees based on current location" feature like Torreya.

**Comment by almasaeed2010** [comment]
We are ready for a Beta release including Larch. 

To Do:

- [ ] Get attribution for "amount of needles" images
- [ ] Release beta and invite Olivia and Jill to preview the app before releasing to production

**Comment by almasaeed2010** [comment]
rolled out to production
