### ISSUE TITLE
Add Vitis spp to the auto-suggestion for "other". 

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#519]
We promised to do this for Margaret Worthington, but it got buried in the FSC issue about adding species. Try this article for getting the native species of grape (i think 6? lets check with ellen): http://palatepress.com/2010/06/wine/wine-indigenous-american-grape-varieties-a-primer/ . When done, email margaret about it.

**Comment by almasaeed2010** [comment]
Added in #522 

Will be available in version 1.4.3 (releasing this week)

**Comment by almasaeed2010** [comment]
rolled out to production
