### ISSUE TITLE
Planted vs Wild item for american chestnut

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#536]
TACF would like to add a question about planted vs wild for users when snapping an american chestnut.

**Comment by almasaeed2010** [comment]
@jwest60 Can you also add this when you can?

All we need is to add a new "select one" question to the American chestnut tree:

"Is this tree wild or has it been planted?"
- [ ] Wild
- [ ] Planted

Then add the new label to MetaLabels.php in the website, and add it to filters as usual.

Thanks.

**Comment by almasaeed2010** [comment]
Merged. Thanks @jwest60
