### ISSUE TITLE
Add TanOak to the list of trees

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#545]
Checklist for the tree is attached below.

[TreeSnap New Tree Checklist_102418.docx](https://github.com/statonlab/Treesnap-mobile/files/2529996/TreeSnap.New.Tree.Checklist_102418.docx)

This needs to be released by mid November.

**Comment by jwest60** [comment]
tanoak added on [this branch](https://github.com/statonlab/Treesnap-mobile/tree/tanoak)

**Comment by jwest60** [comment]
on this branch tanoak is sometimes written as two words instead of one and i think it needs to be changed

**Comment by jwest60** [comment]
tanoak is now written as one word

**Comment by almasaeed2010** [comment]
Thanks! merged #546
