### ISSUE TITLE
Add "what types of trees of same species are nearby?" in oak

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#566]
> Also, our new oak geneticist has a new request for oak- basically just add the "what types of trees of same species are nearby?" question we have for ash and hemlock

**Comment by almasaeed2010** [comment]
@jwest60 You think you can tackle this when you get a chance?

**Comment by jwest60** [comment]
Done. #572

**Comment by almasaeed2010** [comment]
Thanks @jwest60
