### ISSUE TITLE
Editing an observation erases old values

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#609]
The edit form can is malfunctioning. The values are not set properly. 

@jwest60 if you get a chance, take a look at this. You worked before on setting defaults so this should be doable.

**Comment by almasaeed2010** [comment]
If #611 works for you @jwest60, let's start with this issue. It's important we get something out soon to fix this.

**Comment by jwest60** [comment]
i'm having some issues recreating the issue, i tried editing an uploaded observation and changed a value in the edit form, saved, re-uploaded, and it seems the value was changed successfully without changing any of the other values

**Comment by almasaeed2010** [comment]
Check the other species field. Once you create a species and try to edit, the new custom name disappears.

**Comment by jwest60** [comment]
for clarification, you want the user-defined tree species to appear in this list of trees when a user is editing an observation?

![image](https://user-images.githubusercontent.com/32902460/62153598-ecf70a00-b2d2-11e9-9db6-16db72e1eb16.png)

**Comment by almasaeed2010** [comment]
All we need is for the value to show up in the search text box
