### ISSUE TITLE
Creating new filter doesn't automatically get applied to observation list

### ISSUE THREAD

**Issue by mestato** [statonlab/Treesnap-mobile#633]
To recreate the problem:
- go to admin observations page
- click Advanced Filters, provide a name and select some stuff (in my case I named the filter test 2, selected American Chestnuts, state of Kentucky, and dates 6/1/2020-9/9/2020)
- Click apply

At this point there is no message and the observations remain the same (unfiltered). The new filter does not appear in the "Select Advanced Filter" dropdown. 

If you reload the page, the filter appears and can be selected and seems to work. Also, if you go to the Filters page (from the sidebar), it shows up and you can download and it appears to work.

**Comment by almasaeed2010** [comment]
I tested the steps as outlined above but I it got filtered down to ~600 observations. Could you test clearing cache just to rule it out?

Perhaps we can take a look at this during our meeting this Friday to see what we are doing differently.

**Comment by almasaeed2010** [comment]
Fixed and deployed to live site
